# Generated by Django 4.2.30 on 2026-09-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'عضو مقالات برگزیده', 'verbose_name_plural': 'اعضای مقالات برگزیده'},
        ),
    ]
