# Generated by Django 4.2.30 on 2026-07-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter title', max_length=90, unique=True),
        ),
    ]
