# Generated by Django 4.2.30 on 2026-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='my_title', help_text='Enter title', max_length=90, unique=True),
        ),
    ]
