# Generated by Django 4.2.30 on 2026-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_content_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
