# Generated by Django 4.2.30 on 2026-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='بی نام', max_length=33, verbose_name='نام'),
        ),
    ]
